# Verwende ein Basis-Image mit Node.js
FROM node:20-alpine

# Setze das Arbeitsverzeichnis im Container
WORKDIR /app

# Kopiere die Abhängigkeiten
COPY package*.json .

# Installiere die Abhängigkeiten
RUN npm install

# Kopiere den Rest des Backend-Codes
COPY . .



# Exponiere den Port, auf dem der Server läuft
EXPOSE 4242

# SSL-Cert and key
COPY ssl/server.crt /ssl/server.crt
COPY ssl/server.key /ssl/server.key

# Befehl zum Ausführen des Servers
CMD ["npm", "start"]
